name: Docker

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:

  test_autogain:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Run autogain script testing
      run: |
        bash run_autogain_tests.sh
