name: Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:

  test_build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Test Docker Build
      run: docker build --no-cache . --file Dockerfile --tag mikenye/readsb-protobuf:testing

  test_autogain:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Test autogain scripts
      run: bash run_autogain_tests.sh
    