name: Tests

on:
  push:
  pull_request:
    branches:
      - main

jobs:

  test_build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Test Docker Build
      run: docker build --no-cache . --file Dockerfile --tag mikenye/readsb-protobuf:testing

  test_autogain:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Test autogain script
      run: |
        docker build -t readsb_autogain_testing_base .
        docker build -f Dockerfile.autogain_testing -t readsb_autogain_testing .
        time docker run --rm --no-healthcheck readsb_autogain_testing
    